---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy-test
  template:
    metadata:
      labels:
        app: caddy-test
    spec:
      containers:
      - name: caddy
        image: caddy:2-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-test-svc
  namespace: default
spec:
  selector:
    app: caddy-test
  ports:
  - port: 80
    targetPort: 80