---
- name: Update system package cache and perform dist-upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600 # Prevents running 'apt-get update' again if already run within the last hour

- name: Install essential system tools
  ansible.builtin.apt:
    name:
      - curl
      - git
      - htop
      - jq
      - open-iscsi
      - nfs-common # Required later by Kubernetes to mount persistent network storage
    state: present # Ensures packages exist; does nothing if they are already installed